nodeLinker: node-modules   # classic flat node_modules – avoids PnP edge-cases
enableGlobalCache: false   # reproducible builds
# .yarnrc.yml
packageExtensions:
  "@taquito/beacon-wallet@21.0.4":
    peerDependenciesMeta:
      react:
        optional: true
      "react-dom":
        optional: true
      "@testing-library/dom":
        optional: true

